// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CreateRectangle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script>\n      let resizing = false;\n\n      const svg = document.getElementById(\"svg-rectangle\")\n      const rect = document.getElementById(\"rectangle\")\n      const resize_handle = document.getElementById(\"resize-handle\")\n\n      //mouse down\n      resize_handle.addEventListener('mousedown', (e) => {\n         resizing = true;\n         e.preventDefault();\n      })\n\n      //mouse move\n      resize_handle.addEventListener('mousemove', (e) => {\n        \n        if (resizing) {\n            const newWidth = e.clientX - svg.getBoundingClientRect().left\n            const newHeight = e.clientY - svg.getBoundingClientRect().top\n\n            if (newWidth > 50) {\n                rect.setAttribute('width', newWidth)\n                resize_handle.setAttribute('cx', newWidth)\n            }\n\n            if (newHeight > 10) {\n                 rect.setAttribute('height', newHeight)\n                 resize_handle.setAttribute('cy', newHeight)\n            }\n        }\n      })\n\n        // Mouse up event to stop resizing\n    document.addEventListener('mouseup', function() {\n        isResizing = false;\n    });\n\n    </script><svg id=\"svg-rectangle\" width=\"150\" height=\"100\"><rect width=\"150\" height=\"100\" style=\"fill:blue;\" id=\"rectangle\"></rect> <circle id=\"resize-handle\" cx=\"150\" cy=\"100\" r=\"5\" fill=\"red\" cursor=\"nwse-resize\"></circle></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
